<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Launch demo modal</name>
   <tag></tag>
   <elementGuidId>3b352b67-de2a-49c0-b697-b1bfb955db56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-target = '#gridSystemModal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-target=&quot;\#gridSystemModal&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Launch demo modal&quot;i] >> nth=4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d39320d5-721b-498d-9d3c-000ab53bfd79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a2c4bdc-07dd-44cf-8abb-bff43766a953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>28d2493b-c2aa-4042-a2e5-9e267deb2d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>26a6583d-648a-455d-9255-624f6c075704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#gridSystemModal</value>
      <webElementGuid>38593b52-4cdb-4dc3-a537-18992581a182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Launch demo modal</value>
      <webElementGuid>58ebb20e-5b90-4497-acfe-9a769a5d8a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Launch demo modal</value>
      <webElementGuid>aafc75f6-7206-427c-a8b4-f0157f13a94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d93e5a77895bde0d841c6c73cb5cb1f6</value>
      <webElementGuid>48decfec-53d9-4a5f-99c7-8b7314c42cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-target = '#gridSystemModal']</value>
      <webElementGuid>cbc2e740-f3ac-46cf-bd86-e59c484326ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-target = '#gridSystemModal']</value>
      <webElementGuid>4b8aa49f-a039-45d1-a10d-b3c830b58992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Launch demo modal' or . = 'Launch demo modal')]</value>
      <webElementGuid>3f5966b6-10cc-4cd0-b984-37fb071ae413</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
